### ISSUE TITLE
Send Accept request header to support content negotiation

### ISSUE THREAD

**Issue by bvamos** [bcoughlan/openapi-commander#12]
Would be great to set Accept header value from command line (currently it is */*) to support content negotiation.

**Comment by bvamos** [comment]
Merge request has #13 been created

**Comment by bcoughlan** [comment]
After some thought I'm going to remove this option in 3.0.0 and instead add a `-h` / `--header` option to allow overriding any header.

**Comment by bvamos** [comment]
Fine for me, thanks!
