### ISSUE TITLE
JS / TS Public API, alongside CLI

### ISSUE THREAD

**Issue by JulianCataldo** [bcoughlan/openapi-commander#25]
Thanks for this neat project.

Would be nice to use the generator via Node, not only CLI.
I think Vite / Rollup adhere to strict `exports` field in package.json

So `package.json` could be amended:

```jsonc
  "exports": {
    ".": "./src/index.js",
    "./generator": "./src/generator.js",
    // ...
  }
```

Then, we could import it from any project 😄 What do you think?

Bye.

**Comment by bcoughlan** [comment]
Sure thing. I don't have a use case for it personally but I'm happy to accept a PR.
